[gcp_service_account]
type = "service_account"
project_id = "survey-456007"
private_key_id = "c34813de56ca40cdf04baa42de1cf2b92f5ddd21"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvPrRkgcInbiLX
0PLuX/IQBmXMahsG5hbZPmLP+SCLJDJ9K4vGfaqB35AngRZwetULDl38spHWRgDe
b/3D6mrwZEdDR4k3omnJlttN2qwYdtE/f0xmvXwfGwvfxu6lWyNnmZXWwsBzz+24
l+nZ9vHqgaRjwzTQSyaE/AfJ/wxbz6Z7XDGbsZ0TxP9obMApiptigwaeqsvxhmbd
D0epBB0OOiynKvIrLcqRENNRoO9RA06k8TgWG5e2kjIVCbRBazNEoslBCiNsFMu+
BSsIiQs1+6BLpaOxOKpdHxMEre616cRGAqp7gooNsBv/GuS6egvTaxprnShoTo5Z
FRCU7eF5AgMBAAECggEAB/3rUqETRmKQrrht976C5sWv60pUeLRSCu68KWFiYU4R
imFLws3U0o7sP0z1BcSoRhSN5zoKihPPstU3JLHiVhuwn0oaISIkQmgBkNOd4RC8
GrH2vUG7cRy15irnk71sCCu6KFzh03ZCUFaHOOQ45JmscktC85PVyh9HSKg7u00R
3AClc65H5CnKmwvNwmypi9fMPGGJROVPw1VC/jY31BItMRHherLIwtrBA18dC9ni
8hvzEIoGTRJayLLruNJ97+A4EoN9UsXK0uJvO74PUve2X+yfR7SqAExRXXNZ995w
5yg42oro0choTvIiqTL7+iDwXC9o2o5a/Ck6JYTobQKBgQDjNL0qLG/BFZ+g1Eja
Fiq7jpamlw01CaNX4wSCdiFpwpCtsBzP0cKMeZxLsgrD5l1HdEpo+6BdVdu7NI+/
MRF1igGpUZHjR3LXmpRO3cEr1Ot1XhauZ4Bloy9koFSDV97iauw2aX/FlULDLCkC
wwQIjY8Suw0Ph/savArFirCVpQKBgQDFdDBeBlT5vbfWS3hZbsvHtzMY/EO0Hq1y
UtegxsV9HZ9Syf6l3XRIVj0Z6Rw0Xtr64KjDoG/6aDG2UiTSzXqWvwF9lCgdAJVl
oxC+26zSSwaAkh9arMM8Zk9i3VFaeXssaODKN1VqHB1saJwMNWB0oIK2+Ji+tNag
xfx/cIGcRQKBgBtH0NLIhR6c9w67jofJE5Zzl3knN+m/X4KE+pyjjH2DZBXGyJ7X
Y9G0JGUeWpaNCXQz7V9Pn0C1t21x8TSWsq73RB3NcoPkp1Bl+hrCG5iktyTfiD+m
o88QWfduHNesbFGpXvVlk3bo5hxDKCVxvwE75grstLPBsw/RtkVj0rIVAoGAKOTA
Y6jCDpsZKNumiDcnIyyw+3q7duFnoKbBm72vBxOMfLPy9l0gCR87NlOOENaYWZ8P
tLxUlLLhoNXwZGxD+FaEs4JssFz/k/YqsKyEZWU+aoBY2AmxwZ+az2nwwGEqfm8W
JytAmGJMQbiEoQ6o9F6N0+E2mUCQtulqOuaNIVUCgYEAiyx95YFIYL67yszDT4Um
VwXFlzEEjjP8boaqdmCqCR58+/auaXExDNnp/61FVIxONVwBKQ5VqBiDSRO4Aome
kfYx0KEdRbRUVEkAPZb45IxLwX278TFHgQbPrZZPK5zpE6rLGGSWqwJPjKfpfFVP
sjjd2R+WOopQ+sep1PU5/2o=
-----END PRIVATE KEY-----"""
client_email = "surveyjag@survey-456007.iam.gserviceaccount.com"
client_id = "104760377248378170722"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/surveyjag%40survey-456007.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
